"""baseline

Revision ID: 8a53f247ce08
Revises: 
Create Date: 2026-08-30 23:04:43.610497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a53f247ce08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('use_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('idea_initiator', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_added_description', sa.Text(), nullable=True),
    sa.Column('use_category', sa.String(length=50), nullable=False),
    sa.Column('ai_feasibility', sa.String(length=50), nullable=False),
    sa.Column('value_added', sa.String(length=50), nullable=False),
    sa.Column('development_time', sa.String(length=50), nullable=False),
    sa.Column('process_criticality', sa.String(length=50), nullable=False),
    sa.Column('process_dependency', sa.String(length=50), nullable=False),
    sa.Column('economic_value', sa.String(length=50), nullable=False),
    sa.Column('golive_date', sa.String(length=10), nullable=False),
    sa.Column('manual_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_value_votes',
    sa.Column('use_case_id', sa.String(length=36), nullable=False),
    sa.Column('voter', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_cases.id'], ),
    sa.PrimaryKeyConstraint('use_case_id', 'voter')
    )
    op.create_table('use_case_dependencies',
    sa.Column('use_case_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['use_cases.id'], ),
    sa.ForeignKeyConstraint(['use_case_id'], ['use_cases.id'], ),
    sa.PrimaryKeyConstraint('use_case_id', 'depends_on_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_case_dependencies')
    op.drop_table('economic_value_votes')
    op.drop_table('use_cases')
    # ### end Alembic commands ###
